### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Elmit2015** [HelloZeroNet/ZeroBlog#1]
I created the site   siteCreate
I saved public and private key   => yes
I copied all data of 1Blog... to my new site's data/1vkxtW1mwAKdkZFjQsb1oVmdrqLWJDRQp
I copied data/1vkxtW1mwAKdkZFjQsb1oVmdrqLWJDRQp/data-default.json to data.json
I changed within data.json my site's title and description, edit even the first blog post there
I added the site to data/sites.json as:
   "1vkxtW1mwAKdkZFjQsb1oVmdrqLWJDRQp": {
        "auth_key": "xxxxxx", 
        "own": true, 
        "permissions": [], 
        "serving": true, 
        "wrapper_key": "xxxxx"
    },

I signed it again
I started ZeroNet and see the newly blog.
I add a new blog entry and edit (click on the special sign) the headline. I save it! (right lower corner of the screen (did not find that before)
The file data.json got the new blog entry!

Hmm, and HOW can I change the Blog post body???

**Comment by HelloZeroNet** [comment]
You have to click into the blog post (by clicking on the headline), then you can edit the body

**Comment by Elmit2015** [comment]
No, the Edit sign of the body did not appear before. 
You need to save first the headline, then find the Edit sign of the body, then you can change the text!

**Comment by HelloZeroNet** [comment]
Later today i'm going to enable the body editing feature also on main page to prevent confusion.

**Comment by Elmit2015** [comment]
I also get this:

[21:06:07] Site:19Wd2M..wNXd Can't update content.json

**Comment by HelloZeroNet** [comment]
Probably someone modified the 19Wd2M..wNXd site's content.json, but didn't updated the sign.

**Comment by Elmit2015** [comment]
it is my blog, ... I have updated, I have signed WITHIN the blog and even from the terminal:

python zeronet.py siteSign 19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd
- Signing site: 19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd...
  Private key (input hidden):
  Site:19Wd2M..wNXd Opening site data directory: data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd...
  Site:19Wd2M..wNXd - [SKIPPED] data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/content.json
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/index.html (SHA512: a4eef15fa08428ce649105f70ed71e70d50d20cdbeb08a298f2121bc39ca5b9e)
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/data.json (SHA512: dd0d71c03b1ca1f416f4fbe4ec64401b86e547254cf046b1db187f179e2db661)
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/data.json-default (SHA512: 53b13a1d181295af27bdeca328adfe7a45d4784044ce632bc647d5bbf7661831)
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/css/all.css (SHA512: 44fabad626804c820dc6a887449919ff558bcf26722abc5e191853704e76c411)
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/js/all.js (SHA512: e8bdbbe2aedee07e02d8f4021411d654589623aeff5c346e29d0b9ee09d74499)
  Site:19Wd2M..wNXd - data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/img/loading.gif (SHA512: 8a42b98962faea74618113166886be488c09dad10ca47fe97005edc5fb40cc00)
  Site:19Wd2M..wNXd Adding timestamp and sha512sums to new content.json...
  Site:19Wd2M..wNXd Verifying private key...
  Site:19Wd2M..wNXd Signing modified content.json...
  Site:19Wd2M..wNXd Saving to data/19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd/content.json...
  Site:19Wd2M..wNXd Site signed!

Frontend shows:  SEEDING UPDATE FAILED

Backend shows:

python zeronet.py 
[22:07:23] - Creating UiServer....
[22:07:23] - Creating FileServer....
[22:07:23] - Starting servers....
[22:07:23] src.Ui.UiServer --------------------------------------
[22:07:23] src.Ui.UiServer Web interface: http://127.0.0.1:43110/
[22:07:23] src.Ui.UiServer --------------------------------------
[22:07:23] src.File.FileServer Binding to tcp://*:15441
[22:07:24] src.File.FileServer Checking port 15441 using canyouseeme.org...
[22:07:25] src.File.FileServer [OK :)] Port open: Success: I can see your service on 11.22.33.44 on port (15441) Your ISP is not blocking port 15441
[22:07:43] Site:1BoLdX..vrkk [MISSING] High.Maintenance.S04E01.Qasim.mp4
[22:08:55] Site:19Wd2M..wNXd Can't update content.json

**Comment by HelloZeroNet** [comment]
do you have `"own": true` in `data/sites.json` at your site ?

**Comment by Elmit2015** [comment]
```
"19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd": {
    "auth_key": "xxxx", 
    "own": true, 
    "permissions": [], 
    "serving": true, 
    "wrapper_key": "xxxx"
}, 
```

**Comment by HelloZeroNet** [comment]
If its a new site and no one is seeding it yet then its normal: At startup the zeronet tries to download content.json from peers to check if its changed, but if no peers found then it will fail, you can ignore it.

**Comment by Elmit2015** [comment]
OK

In the main page it still says:
SEEDING UPDATE FAILED
ZeroBlog
Blogging Platform Demo
x1 CHANGED 35 MIN AGO

Although data/19W... /data.json says:

{
    "title": "Elmit's ZeroBlog",
    "description": "Elmit's decentralized Blog, a self publishing blogging platform.",
    "links": "- [mininghere.com](http://mininghere.com)\n- [elmit.com](http://elmit.com)",
    "next_id": 3,
    "demo": false,
    "modified": 1422277216,
    "posts": [
        {
            "id": 2,
            "title": "Second blog post ",
            "posted": 1422276046.908,
            "edited": false,
            "body": "Blog post body"
        },
        {
            "id": 1,
            "title": "Hello exciting Blog Reader!",
            "posted": 1422065620.441,
            "edited": false,
            "body": "This is my first post"
        }
    ]
}

**Comment by HelloZeroNet** [comment]
Yes, update failed, because no peers found for the site. If someone starts to seed your site then the notification will be gone at next restart. (or if you force update it using ZeroHello)

In the next version i try to hide this error if the site is your own and no peers found for it.

**Comment by Elmit2015** [comment]
python zeronet.py sitePublish 19Wd2MsWJz2rQv446kQTakrpFZ7aqQwNXd
- Creating FileServer....
  src.File.FileServer Binding to tcp://*:15441
  src.File.FileServer Checking port 15441 using canyouseeme.org...
  src.File.FileServer [OK :)] Port open: Success: I can see your service on 11.22.33.44 on port (15441) Your ISP is not blocking port 15441
- Gathering peers from tracker
  Site:19Wd2M..wNXd Publishing to 20/0 peers...
  Site:19Wd2M..wNXd Successfuly published to 0 peers
- Serving files....

seems also not to help!

**Comment by Elmit2015** [comment]
I am not sure if I can follow here.
Regardless if there is a peer or not, the Hello Zero should always give the right title, but instead it keeps it to ZeroBlog
The bottom of the Link in Hello Zero says x2 - I believe it means 2 peers, and still it says Update Failed. As also the backend says Site:19Wd2M..wNXd Can't update content.json
... even if I restart zeronet.py

**Comment by HelloZeroNet** [comment]
`Publishing to 20/0 peers` means no peers found. If Hello Zero say 2 peers it means you + someone else, but if he is in passive mode or he is not reachable for some other reason then the update will be still failed.

To change the title displayed in zerohello your have to modify the `content.json` file then use the ☰ > Update function in ZeroHello (or restart zeronet.py)

(in the next version i try to make this modification automatically if you change the title displayed in the bolg)

**Comment by ghost** [comment]
same problem here as well... come on can anyone make a forum for http://zeronet.io/ 
because github isn't the place where we should discuss about this.

**Comment by HelloZeroNet** [comment]
Please specify your problem.
You can use [zerotalk](http://127.0.0.1:43110/talk.zeronetwork.bit) or [reddit](https://www.reddit.com/r/zeronet/) if you more comfortable with that

**Comment by calebebrim** [comment]
I've the same problem.
I try the same steps using first machine.
the second one i try to acess the website.

```
./Python/python zeronet.py sitePublish 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Loading site...
- Creating FileServer....
TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 154 > socket.py line 344
FileServer Checking port 15441 using portchecker.co...
FileServer [OK :)] Port open: Port 15441 is open.
- Gathering peers from tracker
Site:1ErAxF..g77E Publishing content.json to 5/1 peers (connected: 0) diffs: [] (0.00k)...
Site:1ErAxF..g77E [FAILED] 189.114.229.135:16881: None
Site:1ErAxF..g77E Successfuly content.json published to 0 peers, publishing to 5 more peers in the background
- No peers found, sitePublish command only works if you already have visitors serving your site
```

and then start zeronet:

```
bash ZeroNet.bash 
- Starting ZeroNet...
[17:07:30] - OpenSSL loaded, version: 0009081DF
[17:07:30] - Version: 0.3.7 r1287, Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)], Gevent: 1.0.2
[17:07:30] - Creating FileServer....
[17:07:30] TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 154 > socket.py line 344
[17:07:30] - Creating UiServer....
[17:07:31] - Removing old SSL certs...
[17:07:31] - Starting servers....
[17:07:31] Ui.UiServer --------------------------------------
[17:07:31] Ui.UiServer Web interface: http://127.0.0.1:43110/
[17:07:31] Ui.UiServer --------------------------------------
[17:07:31] - Opening browser: default_browser...
[17:07:33] FileServer Checking port 15441 using portchecker.co...
[17:07:33] FileServer [OK :)] Port open: Port 15441 is open.

```

on the second machine I've tried to access my published website it says ...

```
CONNECTING...
NO PEERS FOUND
CONTENT.JSON DOWNLOAD FAILED << IN RED
PEERS FOUND: 1  
```

**Comment by HelloZeroNet** [comment]
you need to sign your site every time you modify it: `zeronet.py siteSign address` or using sidebar

**Comment by calebebrim** [comment]
OK...
I think that I did it.

Just in case i will do again

Signing...:

```
../Python/python zeronet.py siteSign 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Signing site: 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E...
Private key (input hidden):
Site:1ErAxF..g77E Opening site data directory: data/1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E/...
Site:1ErAxF..g77E - [SKIPPED] .DS_Store
Site:1ErAxF..g77E - [SKIPPED] content.json
Site:1ErAxF..g77E - index.html (SHA512: 2caba22895170a34d6c33444f3c85b4efb7d783b8933b86a4d3d6bbb46525542)
Site:1ErAxF..g77E - index_sample.html (SHA512: 21c2400fc41c72741f7adc393ff15d74c4c3c5a781e73b97ad8b4a80bee71545)
Site:1ErAxF..g77E - [SKIPPED] lib/.DS_Store
Site:1ErAxF..g77E - lib/jquery.min.js (SHA512: 005c3102459dbf145df6a858629d6a6de4598fafe24cd989d86170731b0c3b3c)
Site:1ErAxF..g77E - lib/jquery.textfill.min.js (SHA512: 3f123a5b5539a7ae89cd39214bca92174c3d488415578eed85a8a558e96bda4e)
Site:1ErAxF..g77E - [SKIPPED] lib/jquery_mobile/.DS_Store
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.css (SHA512: fcc7e3253e88b4f1621080aa6a2d1839f5ddab7062a998687844abe9460446b2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.js (SHA512: 82dededa7474dc53cca2a6f3360c5b0cd00b2185855c24992d441e37b59c1dd3)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.css (SHA512: cf6005395281a9c9681424fe520b3489ca937c2f1f0681aadb33fad0c9444a72)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.js (SHA512: d29ac1d6db5c6f3c2ce9dcc71646daf750456a6c5aa263980259be3e9595da58)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.map (SHA512: 7883393d1177b09e9b0cce48022e91ef5c1ede6fb3147dc69943eb324714264b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.css (SHA512: 5b4571d2bcda7377203d35823795bdf6485b2e7480b56d336fb24b4bf7f8f998)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.min.css (SHA512: 18fe8f35d4b622521cbeaf4dac4b8a6a83cfd733b1c336b0ce14c95fc63bd951)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.css (SHA512: 755df88b405eb4f82e1b7ee34cf6912014da9ff8d882f1b5eea733ef10d30702)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.min.css (SHA512: 203858d6cd81e3e288d690b746b66eb07ada8b2211b6bf66981232785eba11f2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.css (SHA512: a978928de9e6dd7903bb17b49d27c3e1962d1bf403a14df120cb45f34f375b5a)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.min.css (SHA512: 47f33941dc4e4102ff594167554ef0f2448876a4e19efb22d30b8a3b25fc8c3b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.css (SHA512: a3284517f1f3d5c1941e9fe795158369df3ce618260729d42646eff1cc880c98)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.min.css (SHA512: 94017de786151352146f12737fed1cf5d9ee1e1e355aa3ffa88c090dc853070b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.css (SHA512: 62a0b1748dcec66f9fe680ae44fc8d1036eeaaf162e7cbaa69122fa1626a53d1)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.min.css (SHA512: c9c6252ea1d35cf46870a155f2dd02e5f5304efba2bfee26e641d64cde63b949)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.css (SHA512: 4b632d48c0192017785b4c0429bff609a69f8408d92a440bf5924f74b57a7556)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.min.css (SHA512: bf6960d48b13ebcbf6eea57cc99c1c14c6894913660dba74883f7bd088aef7f1)
Site:1ErAxF..g77E Adding timestamp and sha512sums to new content.json...
Site:1ErAxF..g77E Verifying private key...
Site:1ErAxF..g77E Correct 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E in valid signers: ['1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E']
Site:1ErAxF..g77E Signing content.json...
Site:1ErAxF..g77E Saving to content.json...
Site:1ErAxF..g77E File content.json signed!

```

Publishing...:

```
../Python/python zeronet.py sitePublish 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Loading site...
- Creating FileServer....
TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 154 > socket.py line 344
FileServer Checking port 15441 using portchecker.co...
FileServer [OK :)] Port open: Port 15441 is open.
- Gathering peers from tracker
Site:1ErAxF..g77E Publishing content.json to 5/1 peers (connected: 0) diffs: [] (0.00k)...
Site:1ErAxF..g77E [FAILED] 189.114.229.135:16881: None
Site:1ErAxF..g77E Successfuly content.json published to 0 peers, publishing to 5 more peers in the background
- No peers found, sitePublish command only works if you already have visitors serving your site
```

**Comment by HelloZeroNet** [comment]
works here, except 2 files: lib/jquery_mobile/images/ajax-loader.gif, index_sample.html (probably you have modified it after the signing)

you can sign and publish in one step using `zeronet.py siteSign site privatekey --publish`

**Comment by calebebrim** [comment]
ok.. 
I didn't change anything, but its ok I will try.

```
../Python/python zeronet.py siteSign 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E --publish
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Signing site: 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E...
Private key (input hidden):
Site:1ErAxF..g77E Opening site data directory: data/1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E/...
Site:1ErAxF..g77E - [SKIPPED] .DS_Store
Site:1ErAxF..g77E - [SKIPPED] content.json
Site:1ErAxF..g77E - index.html (SHA512: 2caba22895170a34d6c33444f3c85b4efb7d783b8933b86a4d3d6bbb46525542)
Site:1ErAxF..g77E - [SKIPPED] lib/.DS_Store
Site:1ErAxF..g77E - lib/jquery.min.js (SHA512: 005c3102459dbf145df6a858629d6a6de4598fafe24cd989d86170731b0c3b3c)
Site:1ErAxF..g77E - lib/jquery.textfill.min.js (SHA512: 3f123a5b5539a7ae89cd39214bca92174c3d488415578eed85a8a558e96bda4e)
Site:1ErAxF..g77E - [SKIPPED] lib/jquery_mobile/.DS_Store
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.css (SHA512: fcc7e3253e88b4f1621080aa6a2d1839f5ddab7062a998687844abe9460446b2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.js (SHA512: 82dededa7474dc53cca2a6f3360c5b0cd00b2185855c24992d441e37b59c1dd3)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.css (SHA512: cf6005395281a9c9681424fe520b3489ca937c2f1f0681aadb33fad0c9444a72)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.js (SHA512: d29ac1d6db5c6f3c2ce9dcc71646daf750456a6c5aa263980259be3e9595da58)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.map (SHA512: 7883393d1177b09e9b0cce48022e91ef5c1ede6fb3147dc69943eb324714264b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.css (SHA512: 5b4571d2bcda7377203d35823795bdf6485b2e7480b56d336fb24b4bf7f8f998)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.min.css (SHA512: 18fe8f35d4b622521cbeaf4dac4b8a6a83cfd733b1c336b0ce14c95fc63bd951)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.css (SHA512: 755df88b405eb4f82e1b7ee34cf6912014da9ff8d882f1b5eea733ef10d30702)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.min.css (SHA512: 203858d6cd81e3e288d690b746b66eb07ada8b2211b6bf66981232785eba11f2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.css (SHA512: a978928de9e6dd7903bb17b49d27c3e1962d1bf403a14df120cb45f34f375b5a)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.min.css (SHA512: 47f33941dc4e4102ff594167554ef0f2448876a4e19efb22d30b8a3b25fc8c3b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.css (SHA512: a3284517f1f3d5c1941e9fe795158369df3ce618260729d42646eff1cc880c98)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.min.css (SHA512: 94017de786151352146f12737fed1cf5d9ee1e1e355aa3ffa88c090dc853070b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.css (SHA512: 62a0b1748dcec66f9fe680ae44fc8d1036eeaaf162e7cbaa69122fa1626a53d1)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.min.css (SHA512: c9c6252ea1d35cf46870a155f2dd02e5f5304efba2bfee26e641d64cde63b949)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.css (SHA512: 4b632d48c0192017785b4c0429bff609a69f8408d92a440bf5924f74b57a7556)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.min.css (SHA512: bf6960d48b13ebcbf6eea57cc99c1c14c6894913660dba74883f7bd088aef7f1)
Site:1ErAxF..g77E Adding timestamp and sha512sums to new content.json...
Site:1ErAxF..g77E Verifying private key...
Site:1ErAxF..g77E Private key invalid! Valid signers: ['1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E'], Private key address: False
Calebes-MBP:ZeroNet calebebrim$ ../Python/python zeronet.py siteSign 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E --publish
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Signing site: 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E...
Private key (input hidden):
Site:1ErAxF..g77E Opening site data directory: data/1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E/...
Site:1ErAxF..g77E - [SKIPPED] .DS_Store
Site:1ErAxF..g77E - [SKIPPED] content.json
Site:1ErAxF..g77E - index.html (SHA512: 2caba22895170a34d6c33444f3c85b4efb7d783b8933b86a4d3d6bbb46525542)
Site:1ErAxF..g77E - [SKIPPED] lib/.DS_Store
Site:1ErAxF..g77E - lib/jquery.min.js (SHA512: 005c3102459dbf145df6a858629d6a6de4598fafe24cd989d86170731b0c3b3c)
Site:1ErAxF..g77E - lib/jquery.textfill.min.js (SHA512: 3f123a5b5539a7ae89cd39214bca92174c3d488415578eed85a8a558e96bda4e)
Site:1ErAxF..g77E - [SKIPPED] lib/jquery_mobile/.DS_Store
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.css (SHA512: fcc7e3253e88b4f1621080aa6a2d1839f5ddab7062a998687844abe9460446b2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.js (SHA512: 82dededa7474dc53cca2a6f3360c5b0cd00b2185855c24992d441e37b59c1dd3)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.css (SHA512: cf6005395281a9c9681424fe520b3489ca937c2f1f0681aadb33fad0c9444a72)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.js (SHA512: d29ac1d6db5c6f3c2ce9dcc71646daf750456a6c5aa263980259be3e9595da58)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile-1.4.5.min.map (SHA512: 7883393d1177b09e9b0cce48022e91ef5c1ede6fb3147dc69943eb324714264b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.css (SHA512: 5b4571d2bcda7377203d35823795bdf6485b2e7480b56d336fb24b4bf7f8f998)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.external-png-1.4.5.min.css (SHA512: 18fe8f35d4b622521cbeaf4dac4b8a6a83cfd733b1c336b0ce14c95fc63bd951)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.css (SHA512: 755df88b405eb4f82e1b7ee34cf6912014da9ff8d882f1b5eea733ef10d30702)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.icons-1.4.5.min.css (SHA512: 203858d6cd81e3e288d690b746b66eb07ada8b2211b6bf66981232785eba11f2)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.css (SHA512: a978928de9e6dd7903bb17b49d27c3e1962d1bf403a14df120cb45f34f375b5a)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-png-1.4.5.min.css (SHA512: 47f33941dc4e4102ff594167554ef0f2448876a4e19efb22d30b8a3b25fc8c3b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.css (SHA512: a3284517f1f3d5c1941e9fe795158369df3ce618260729d42646eff1cc880c98)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.inline-svg-1.4.5.min.css (SHA512: 94017de786151352146f12737fed1cf5d9ee1e1e355aa3ffa88c090dc853070b)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.css (SHA512: 62a0b1748dcec66f9fe680ae44fc8d1036eeaaf162e7cbaa69122fa1626a53d1)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.structure-1.4.5.min.css (SHA512: c9c6252ea1d35cf46870a155f2dd02e5f5304efba2bfee26e641d64cde63b949)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.css (SHA512: 4b632d48c0192017785b4c0429bff609a69f8408d92a440bf5924f74b57a7556)
Site:1ErAxF..g77E - lib/jquery_mobile/jquery.mobile.theme-1.4.5.min.css (SHA512: bf6960d48b13ebcbf6eea57cc99c1c14c6894913660dba74883f7bd088aef7f1)
Site:1ErAxF..g77E Adding timestamp and sha512sums to new content.json...
Site:1ErAxF..g77E Verifying private key...
Site:1ErAxF..g77E Correct 1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E in valid signers: ['1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E']
Site:1ErAxF..g77E Signing content.json...
Site:1ErAxF..g77E Saving to content.json...
Site:1ErAxF..g77E File content.json signed!
- Loading site...
- Creating FileServer....
TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 154 > socket.py line 344
FileServer Checking port 15441 using portchecker.co...
FileServer [OK :)] Port open: Port 15441 is open.
- Gathering peers from tracker
Site:1ErAxF..g77E Publishing content.json to 5/2 peers (connected: 0) diffs: [] (0.00k)...
Site:1ErAxF..g77E [FAILED] 189.114.229.135:16881: None
Site:1ErAxF..g77E [OK] 192.210.179.116:15441: Thanks, file content.json updated! 1/5
Site:1ErAxF..g77E Successfuly content.json published to 1 peers, publishing to 5 more peers in the background
- Serving files (max 60s)...
- Done.

```

It seems that it works, but not totally. 
I've started the zeronet locally.

Now I can acess my page using the other computer; but, it says that 3 file update failed. 
What does it means?

The remote page says that ajax-loader.gif couldn't be loaded.

**Comment by HelloZeroNet** [comment]
it means ajax-loader.gif is referenced somewhere in the source code in the site, but it's not signed. you can see the missing files using the sidebar (drag the topright zero button to left)

**Comment by calebebrim** [comment]
I think I found what is wrong. The referenced file doesn't exist on folder structure.
I thought that content.json were updated automatically. It's ok to remove all files from content.json and let siteSign command recreate it?

**Comment by HelloZeroNet** [comment]
Yes, you can remove it, but not necessary, if you delete a file and re-sign it will be automatically removed from content.json as well

**Comment by calebebrim** [comment]
Ok... Thank you!
There is other problem, but I think that is better open a new issue.
