### ISSUE TITLE
Pluralization of “Comment”

### ISSUE THREAD

**Issue by kseistrup** [HelloZeroNet/ZeroBlog#12]
Currently ZeroBlog pluralizes the word “Comment” no matter what the number of comments for a given blog entry actually is. IMHO, it would look much neater if ZeroBlog took the trouble and used the word “Comment” for when there is exactly 1 comment, and “Comments” for all other cases.

**Comment by obv-mikhail** [comment]
The "Comments" refer to a section of the website. It doesn't make sense for it to be singular even if the section contains just one comment.

**Comment by kseistrup** [comment]
I disagree. When I visit an entry of a ZeroBlog, I see:

```
This is the entry title
2 hours ago · 🗩 1 Comments ♡

This is the body text
```

**Comment by obv-mikhail** [comment]
Alright yes you are correct, I should have checked the context.

**Comment by kseistrup** [comment]
I should probably have been more specific.

**Comment by obv-mikhail** [comment]
This should work https://github.com/HelloZeroNet/ZeroBlog/pull/13 .

**Comment by HelloZeroNet** [comment]
https://github.com/HelloZeroNet/ZeroBlog/commit/5befe369f43cda46a600a7075b078060bf972f0d
