### ISSUE TITLE
table

### ISSUE THREAD

**Issue by ulrichard** [HelloZeroNet/ZeroBlog#22]
In the index.html file there is a small documentation of the markdown.
Is that everything there is, or is there some way of inserting a table?
I would like this post
http://127.0.0.1:43110/ulrichard.bit
to look like this post
https://ulrichard.ch/blog/?p=2105

**Comment by HelloZeroNet** [comment]
Yes, example: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables
If you need advanced formatting (eg cell background), you can use html code directly
