### ISSUE TITLE
Can't edit comments in Chrome

### ISSUE THREAD

**Issue by jerry-wolf** [HelloZeroNet/ZeroBlog#36]
If I submit a comment then click edit button, the page becomes that.
![edit](https://cloud.githubusercontent.com/assets/18724949/21939007/c5e18202-d9f8-11e6-8ff2-f2b157992efd.png)
Platform: Windows 10, 57.0.2979.0 dev
I can edit the comment normally in Firefox. And If I edited the comment in Firefox, the comment will be editable in Chrome.

**Comment by HelloZeroNet** [comment]
It should work now https://github.com/HelloZeroNet/ZeroBlog/commit/eeb5d7b4771b8b584247bfb0fad5999966af0b59

(looks like for some reasons chrome is ignorig z-index if css transform is specified)
