### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Snarkly** [HelloZeroNet/ZeroBlog#42]
Please add Drag and Drop features to ZeroBlog like this site has http://sitebuilder.simplereg.com/en/brand/1421/ for non-coders. Maybe you can add two buttons to the pull out side panel that switches the panel from a peers mode to a edit mode like this example picture. ![zblog3](https://cloud.githubusercontent.com/assets/8492776/25014171/a7e2db10-2044-11e7-97db-11c33349a261.png)

**Comment by HelloZeroNet** [comment]
The html editor is totally out of scope from the main client and it should be in the site's source code instead of client's.

**Comment by Snarkly** [comment]
Then please try to figure out another way to make it drag and drop for non-coders. I've promoted your project for two years and during that time I haven't even been able to use the ZeroBlog myself. I will no longer promote ZeroNet till it has features like these.
