### ISSUE TITLE
universal admin interface: to see user comments, limits, delete comments

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [HelloZeroNet/ZeroBlog#6]
user story:
 I have just banned a user from my blog
 he posted first elsewhere several times his love for the 4-letter word starting with f and ending with uck
but: I can not delete his comment in the blog now

**Comment by HelloZeroNet** [comment]
We need to create a tool that able to display an admin interface based on xml/json or yaml files that is defines the site's table structure, so it's suitable for any zeronet site. It requires lots of work, but worth it.

**Comment by wpstudio** [comment]
I agree with this next step for the code.

**Comment by HelloZeroNet** [comment]
Created an issue for it: https://github.com/HelloZeroNet/ZeroNet/issues/354
