### ISSUE TITLE
Language File value problem

### ISSUE THREAD

**Issue by MofuMoca** [HelloZeroNet/ZeroBlog#68]
![issuse01](https://user-images.githubusercontent.com/1411400/50386659-6ff52800-0726-11e9-9e02-4166b56f2882.png)

as picture  
If set "Comments" any value,it will replace id of "0 Comments:"  
but remove it works well.
![issuse02](https://user-images.githubusercontent.com/1411400/50386704-2b1dc100-0727-11e9-8931-c8c120a194d1.png)

**Comment by tangdou1** [comment]
it can be closed
