### ISSUE TITLE
Content signing failed Include too large 20302B > 10000B

### ISSUE THREAD

**Issue by tlaurion** [HelloZeroNet/ZeroBlog#75]
This happens on all the posts already created for which I try to comment on.
Any idea why that happens?

Not happening on new posts... Which are under the Include too large 10000B limit.
How to raise it? 

Upgraded ZeroBlog code. Still not working
127.0.0.1:43110/1DMb3CV66qZPwJqkgm4z12nu8BrAwDoD4g/

**Comment by filips123** [comment]
You probably need to raise your own limit comments limit.

Edit `data/users/content.json` in your site directory and add a new entry under the `permissions` section with your ID and bigger `max_size`. Then sign and publish that file.

Something like `"your-id@zeroid.bit": {"max_size": 50000}` for 50KB of data.

But I still don't know why you can comment on new posts. Please try my suggestion and it doesn't work there is probably some bug with ZeroBlog.
