### ISSUE TITLE
Make ZeroBlog mobile-friendly.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroBlog#77]
There are numerous forks of ZeroBlog that are.

You should also add

 "viewport": "width=device-width, initial-scale=0.8, user-scalable=0",

to content.json

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, I have added a layout for smaller screens: https://github.com/HelloZeroNet/ZeroBlog/commit/080c4e4904f5fbc6b75c04dfeb3fed52b5e2b3ed

**Comment by styromaniac** [comment]
> Thanks for the suggestion, I have added a layout for smaller screens: [080c4e4](https://github.com/HelloZeroNet/ZeroBlog/commit/080c4e4904f5fbc6b75c04dfeb3fed52b5e2b3ed)

You need to refine the dark theme for it. The hamburger menu text is unreadable.
