### ISSUE TITLE
Mobile dark mode needs refinement.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroBlog#79]
![Screenshot_20200712-170021](https://user-images.githubusercontent.com/43807387/87256502-47946200-c461-11ea-9121-ea367bde100c.png)

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed by https://github.com/HelloZeroNet/ZeroBlog/commit/389acfbe21bec910cdefcef43e9a515ad32187dc
