### ISSUE TITLE
Need help on how to decrease my website Load time

### ISSUE THREAD

**Issue by himanshuseo1** [HelloZeroNet/ZeroBlog#80]
hello guys

need suggestions on how to speed up website load time. on google speed test we have following results for [my wesbite
](https://propliners.in/)

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpropliners.in%2F

Reduce initial server response time
1.88 s
Remove unused JavaScript
0.75 s
Remove unused CSS
0.45 s
Defer offscreen images
0.3 s

the above mentioned are the main factor.
i am using wordpress, using autoptimize plugin but load time is still high.

**Comment by HelloZeroNet** [comment]
I think its not related to the project
